site_name: cgcnn2
site_url: https://jcwang587.github.io/cgcnn2
repo_url: https://github.com/jcwang587/cgcnn2
repo_name: cgcnn2

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true

nav:
  - Home: index.md
  - CGCNN2: 1_cgcnn.md
  - Installation: 2_installation.md
  - Usage: 3_usage.md
  - Examples: 4_examples.md
  - API Reference: 5_api_reference.md
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jcwang587/cgcnn2 

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js